### PR TITLE
Selected text in input field removed during set value 

### PR DESCRIPTION
**Pull request by shuboy2014**
I have updated the content.js file in which during set value of clicked element (input field)  the requested link will be set in place of selected text  .

### CODE REVIEW

**Comment by sahildua2305** [comment]
@shuboy2014 can you please update your PR with only the required changes. It's difficult to review the changes like this since there are a lot of indentation changes.

I'll however, add editor config file for this project to eliminate such issues in future.

**Comment by shuboy2014** [comment]
@sahildua2305  I have updated .

**Comment by sahildua2305** [comment]
What have you updated @shuboy2014 ? There are still a lot of indentation changes in the diff.

**Comment by sahildua2305** [comment]
Closing this PR as the issue has been resolved in #13

**Pull request closed without merging**
